### ISSUE TITLE
Don't put secrets in the built image

### ISSUE THREAD

**Issue by Highfire1** [langaracpsc/langaracpsc-next#12]
In `.github/workflows/main.yml` the workflow injects the APIURL and APIKEY into the container, which is then publically published.

**Comment by rishit-singh** [comment]
Might wanna use an actual keyvault then, i'll find one.

**Comment by Highfire1** [comment]
i did ask if .env files were adequate a while ago :s 

also dont forget to reach out to potential hackathon teammate

**Comment by Highfire1** [comment]
fixed.
