### ISSUE TITLE
api is down

### ISSUE THREAD

**Issue by Highfire1** [langaracpsc/langaracpsc-next#39]
Both `/about` and `/events` are stuck on Loading

![image](https://github.com/langaracpsc/langaracpsc-next/assets/45698812/800df320-aa1f-4f2d-b6f0-4f7918aeeed8)

**Comment by Owslebury** [comment]
@Highfire1 hey man can you look at the pull request I made

**Comment by Highfire1** [comment]
@rishit-singh close the issue if its fixed
