### ISSUE TITLE
Website needs a footer

### ISSUE THREAD

**Issue by Highfire1** [langaracpsc/langaracpsc-next#9]
for additional links such as but not limited to:
- copyright
- links to resources such as the planner and transfer docs
- link to club rules
- more social media links (yt, linkedin, potentially medium)
- links to clubs general feedback form (https://forms.gle/jaYbdo6KWbGFvJJG8)

See some of the following for inspiration:
- https://ubccsss.org/
- https://nwhacks.io/

**Comment by rishit-singh** [comment]
MVP done, just needs cleanup

**Comment by rishit-singh** [comment]
Will be done sometime this week

**Comment by Highfire1** [comment]
fyi you can add commits to github issues by putting the issue number in the commit
